spring:
  application:
    name: postgresql-example
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://aje-1.cjglxodge3ei.us-east-2.rds.amazonaws.com:5432/ZuperBodegas
    username: postgres
    password: aje12345
    continueOnError: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
